---
name: Lint Dockerfile

on: [push, pull_request]

jobs:
  lint:
    name: Lint Dockerfile with hadolint
    strategy:
      matrix:
        dockerfile:
          - 5.0/apache/Dockerfile
          - 5.0/fpm-alpine/Dockerfile
          - 5.0/fpm/Dockerfile
          - 6.0/apache/Dockerfile
          - 6.0/fpm-alpine/Dockerfile
          - 6.0/fpm/Dockerfile
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: ${{ matrix.dockerfile }}
          ignore: "DL4006,DL3008,DL3018"
