services:
  limesurvey:
    build:
      context: 6.0/apache/
      dockerfile: Dockerfile
    volumes:
      # TODO Update storage location as desired
      - ./lime-data/surveys:/var/www/html/upload/surveys
    networks:
      - limesurvey-db
    depends_on:
      - lime-db
    ports:
      - "8080:8080"
    environment:
      - "DB_TYPE=pgsql"
      - "DB_PORT=5432"
      - "DB_HOST=lime-db"
      # TODO set passwords
      # - "DB_PASSWORD="
      # - "ADMIN_PASSWORD="
  lime-db:
    image: postgres:17
    volumes:
      - ./lime-data/postgres:/var/lib/postgresql/data
    networks:
      - limesurvey-db
    environment:
      - "POSTGRES_DB=limesurvey"
      - "POSTGRES_USER=limesurvey"
      # TODO set passwords
      # - "POSTGRES_PASSWORD="

networks:
  limesurvey-db:
    driver: bridge
