services:
  limesurvey:
    build:
      context: 6.0/apache/
      dockerfile: Dockerfile
    volumes:
      # TODO Update storage location as desired
      - ./surveys:/var/www/html/upload/surveys
    networks:
      - limesurvey-db
    ports:
      - "8080:8080"
    environment:
      - "DB_HOST=lime-db"
      - "DB_PASSWORD=test"
      - "ADMIN_PASSWORD=test"
  lime-db:
    image: mariadb:11.4
    networks:
      - limesurvey-db
    environment:
      - "MYSQL_USER=limesurvey"
      - "MYSQL_DATABASE=limesurvey"
      - "MYSQL_ROOT_PASSWORD=test"
      - "MYSQL_PASSWORD=test"

networks:
  limesurvey-db:
    driver: bridge
